name: WinGet Manifests

on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  run:
    name: Parse WinGet Manifests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup install 1.80

      - name: Build
        run: |
          git clone https://github.com/microsoft/winget-pkgs.git
          cargo run --release
